runners:
  gpu-runner:
    labels: [self-hosted, cirun, linux, x64, gpu, gcp]
    env:
      GCP_ARTIFACT_REGION: us-central1
      GCP_PROJECT: gpu-test-runners
      REPOSITORY: rag-bench
      PACKAGE: rag-bench-gpu-tests
      VERSION: 0804786
    provider:
      name: gcp
      project: gpu-test-runners
      region: us-central1
      zone: us-central1-b
    machine:
      type: n1-standard-4
      gpu:
        type: nvidia-tesla-t4
        count: 1
      image:
        family: rag-bench-gpu-host
        project: gpu-test-runners
      serviceAccount: gpu-test-runners-sa@gpu-test-runners.iam.gserviceaccount.com
      serviceAccountScopes: [cloud-platform]
      username: ci-gpu-runner
    setup:
      - name: Authenticate Docker to Artifact Registry and pre-pull image
        run: |
          set -euo pipefail
          HOST="${GCP_ARTIFACT_REGION:-us-central1}-docker.pkg.dev"
          PROJECT="${GCP_PROJECT:-gpu-test-runners}"
          IMAGE_REF="${HOST}/${PROJECT}/${REPOSITORY}/${PACKAGE}:${VERSION}"
          gcloud auth configure-docker ${HOST} --quiet
          docker pull "${IMAGE_REF}"
